import React, { type FC } from 'react';
import styles from './element.module.css';

interface Props {
  displayName?: string;
}

const App: FC<Props> = ({ displayName = `Your Widget's Title` }) => {
  return (
    <div className={styles.root}>
      <h2>{displayName}</h2>
      <hr />
      <p>
        This is a Site Widget generated by Wix CLI.<br />
        Continue to develop this widget at <code>'src/site/widgets/custom-elements/my-widget'</code>.
      </p>
    </div>
  );
};

export default App;
